export const tags = [
    {
        name: "General",
        color: "#7e7e7e",
        backgroundColor: "#eeeeee",
        textColor: "white",
    },
    {
        name: "Work",
        color: "#0000FF",
        backgroundColor: "#dadaff",
        textColor: "white",
    },
    {
        name: "Study",
        color: "#00FF00",
        backgroundColor: "#dbfcdb",
        textColor: "black",
    },
    {
        name: "Meeting",
        color: "#800000",
        backgroundColor: "#fae9e9",
        textColor: "white",
    },
    {
        name: "Project",
        color: "#800080",
        backgroundColor: "#ecd5ec",
        textColor: "white",
    },
    {
        name: "Ideas",
        color: "#FF4500",
        backgroundColor: "#fae2d9",
        textColor: "white",
    },
    {
        name: "Research",
        color: "#008000",
        backgroundColor: "#e0f1e0",
        textColor: "white",
    },
    {
        name: "To-do",
        color: "#e44660",
        backgroundColor: "#fde5ea",
        textColor: "white",
    },
    {
        name: "Goals",
        color: "#FFFF00",
        backgroundColor: "#ffffef",
        textColor: "black",
    },
    {
        name: "Important",
        color: "#FF0000",
        backgroundColor: "#fae0e0",
        textColor: "white",
    },
    {
        name: "Priority",
        color: "#1E90FF",
        backgroundColor: "#d9e5f0",
        textColor: "white",
    },
    {
        name: "Personal",
        color: "#00FFFF",
        backgroundColor: "#e3ffff",
        textColor: "black",
    },
    {
        name: "Health",
        color: "#FF69B4",
        backgroundColor: "#fdd3e8",
        textColor: "white",
    },
    {
        name: "Finance",
        color: "#32CD32",
        backgroundColor: "#c4ddc4",
        textColor: "white",
    },
    {
        name: "Quotes",
        color: "#FF6347",
        backgroundColor: "#fde3df",
        textColor: "white",
    },
    {
        name: "Inspiration",
        color: "#FF1493",
        backgroundColor: "#ffcde8",
        textColor: "white",
    },
    {
        name: "Books",
        color: "#FFD700",
        backgroundColor: "#fdf8d8",
        textColor: "black",
    },
    {
        name: "Travel",
        color: "#00a0d1",
        backgroundColor: "#c5d0d3",
        textColor: "white",
    },
    {
        name: "Recipes",
        color: "#FF00FF",
        backgroundColor: "#ffc7ff",
        textColor: "white",
    },
    {
        name: "Contacts",
        color: "#afff47",
        backgroundColor: "#ebfad8",
        textColor: "black",
    },
    {
        name: "Events",
        color: "#923a66",
        backgroundColor: "#e2bbcf",
        textColor: "white",
    },
];
